name: WM_Digital_Assets_Strat
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - altair=6.0.0
  - archspec=0.2.5
  - attrs=25.4.0
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.2
  - azure-identity-cpp=1.13.3
  - azure-storage-blobs-cpp=12.16.0
  - azure-storage-common-cpp=12.12.0
  - azure-storage-files-datalake-cpp=12.14.0
  - babel=2.18.0
  - backports.zstd=1.3.0
  - beautifulsoup4=4.14.3
  - blinker=1.9.0
  - boltons=25.0.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cachetools=6.2.6
  - certifi=2026.1.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.1
  - conda=26.1.0
  - conda-libmamba-solver=25.11.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - contourpy=1.3.3
  - cpp-expected=1.3.1
  - cycler=0.12.1
  - distro=1.9.0
  - et_xmlfile=2.0.0
  - fmt=12.1.0
  - fonttools=4.61.1
  - freetype=2.14.1
  - frozendict=2.4.7
  - gflags=2.2.2
  - gitdb=4.0.7
  - gitpython=3.1.46
  - glog=0.7.1
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.11
  - importlib-metadata=8.7.0
  - jinja2=3.1.6
  - joblib=1.5.3
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jsonschema=4.26.0
  - jsonschema-specifications=2025.9.1
  - kiwisolver=1.4.9
  - krb5=1.22.2
  - lcms2=2.18
  - lerc=4.0.0
  - libabseil=20260107.1
  - libarchive=3.8.5
  - libarrow=23.0.1
  - libarrow-acero=23.0.1
  - libarrow-compute=23.0.1
  - libarrow-dataset=23.0.1
  - libarrow-substrait=23.0.1
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcurl=8.18.0
  - libcxx=21.1.8
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.4
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.78.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.3
  - liblapack=3.11.0
  - liblzma=5.8.2
  - libmamba=2.5.0
  - libmamba-spdlog=2.5.0
  - libmambapy=2.5.0
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=23.0.1
  - libpng=1.6.55
  - libprotobuf=6.33.5
  - libre2-11=2025.11.05
  - libsolv=0.7.35
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libutf8proc=2.11.3
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - lxml=6.0.2
  - lz4-c=1.10.0
  - lzo=2.10
  - markupsafe=3.0.3
  - matplotlib-base=3.10.8
  - menuinst=2.4.2
  - msgpack-python=1.1.2
  - multitasking=0.0.12
  - munkres=1.1.4
  - narwhals=2.16.0
  - ncurses=6.5
  - nlohmann_json=3.12.0
  - nlohmann_json-abi=3.12.0
  - numpy=2.4.2
  - openjpeg=2.5.4
  - openpyxl=3.1.5
  - openssl=3.6.1
  - orc=2.2.2
  - packaging=26.0
  - pandas=2.3.3
  - pandas-datareader=0.10.0
  - patsy=1.0.2
  - pillow=12.1.1
  - pip=26.0.1
  - platformdirs=4.9.2
  - plotly=6.5.2
  - plotly_express=0.4.1
  - pluggy=1.6.0
  - prometheus-cpp=1.3.0
  - protobuf=6.33.5
  - pthread-stubs=0.4
  - pyarrow=23.0.1
  - pyarrow-core=23.0.1
  - pybind11-abi=11
  - pycoingecko=3.2.0
  - pycosat=0.6.6
  - pycparser=2.23
  - pydeck=0.9.1
  - pyfinance=1.3.0
  - pyparsing=3.3.2
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.3
  - python_abi=3.11
  - pytz=2025.2
  - pyyaml=6.0.3
  - qhull=2020.2
  - re2=2025.11.05
  - readline=8.3
  - referencing=0.37.0
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.5
  - rpds-py=0.30.0
  - ruamel.yaml=0.18.17
  - ruamel.yaml.clib=0.2.15
  - scikit-learn=1.8.0
  - scipy=1.17.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=82.0.0
  - simdjson=4.2.4
  - six=1.17.0
  - smmap=6.0.0
  - snappy=1.2.2
  - soupsieve=2.8.3
  - spdlog=1.17.0
  - statsmodels=0.14.6
  - streamlit=1.54.0
  - tenacity=9.1.4
  - threadpoolctl=3.6.0
  - tk=8.6.15
  - toml=0.10.2
  - tornado=6.5.4
  - tqdm=4.67.3
  - truststore=0.10.4
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - unicodedata2=17.0.1
  - urllib3=2.6.3
  - watchdog=6.0.0
  - wheel=0.46.3
  - xlrd=2.0.2
  - xmltodict=1.0.3
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.3.3
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - curl-cffi==0.13.0
      - peewee==3.19.0
      - websockets==16.0
      - yfinance==1.2.0
      - streamlit_option_menu=0.4.0
